# Site settings
title: byte me;
email: adi.version1@gmail.com
author: Aditya Raghuwanshi
description: > # this means to ignore newlines until "baseurl:"
  The ramblings and code smells of Aditya Raghuwanshi
baseurl: "/blag" # the subpath of your site, e.g. /blog/
url: "http://adityar.com" # the base hostname & protocol for your site
twitter_username: royalgoombah
github_username:  kitwalker12

# Build settings
markdown: kramdown

permalink: /:title
paginate: 10
paginate_path: /page/:num
